sudo: false
language: cpp
osx_image: xcode11 # at least until travis default osx version works
jobs:
    include:
        - os: linux
          compiler: gcc
        - os: linux
          compiler: clang
        - os: linux
          compiler: clang
          arch: arm64
        - os: osx
          compiler: clang
#before_install:
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt install libncurses-dev; fi
script:
  - cmake . && cmake --build .
